### PR TITLE
fix: Allow configuration script to run even if SDK is initially disabled in project settings

### LINKED ISSUE #255: Configuration script is not executed if the SDK is disabled in project settings
The configuration script appears to be ineffective if the SDK is not initially enabled in the project settings. Given that a user could potentially set the SDK to enabled in the configuration script, it is necessary that we run the script and verify the value of `enabled`.

### PR DESCRIPTION
**Pull request by limbonaut**
- Fixes #255

### CODE REVIEW

File: src/sentry/sentry_sdk.cpp [hunk 1]
```diff
@@ -207,50 +207,58 @@ PackedStringArray SentrySDK::_get_global_attachments() {
 void SentrySDK::_initialize() {
 	sentry::util::print_debug("starting Sentry SDK version " + String(SENTRY_GODOT_SDK_VERSION));
 
+	// Initialize user if it wasn't set explicitly in the configuration script.
```
Comment (limbonaut) [inline src/sentry/sentry_sdk.cpp:210]: Moved to the top of the function – need to initialize user instance before we exit from the function.

**Review by jpnurmi — APPROVED** [review]
