### PR TITLE
fix: Sanitize Variant values on Android

### LINKED ISSUE #389: Local variables on Android incorrectly displayed as null
In Android issues, GDScript local and member variables with variant type `Object` are always displayed as `null` regardless of actual value.

### PR DESCRIPTION
**Pull request by limbonaut**
Sanitize Variant values on Android, specifically contexts and local variable values. This is important as certain Godot types cannot be converted to Android types, resulting in them being passed as nulls to the bridge layer.  Also, introduce a tool to project for monkey-testing contexts with diverse value types.
- Fixes #389

---

> [!NOTE]
> Sanitizes Android Variant payloads (contexts, exception vars) and adds a demo "Tools" tab with buttons to run tests and send diverse context.
> 
> - **Android**:
>   - Add `sanitize_variant` in `src/sentry/android/android_util.{h,cpp}` to normalize non-primitive `Variant` types and limit depth.
>   - Use sanitization in `AndroidSDK.set_context(...)` and `AndroidEvent.merge_context(...)` to prevent nulls, and when serializing exception `vars` in `AndroidEvent::add_exception`.
> - **Demo (project)**:
>   - Replace `TabContainer/Tests` with `TabContainer/Tools`; show `%RunTestsButton` only if `res://test/mobile_tests.gd` exists.
>   - Add `TestDiverseContextButton` and `_on_test_diverse_context_button_pressed()` in `project/mobile.{tscn,gd}` to set `SentrySDK.set_context("diverse_context", ...)` with varied types and capture a message.
> - **Docs/Meta**:
>   - Update `CHANGELOG.md` with Android sanitization and context/local variable fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 685c35ec037644f3b17c6f2bac3fc51bc117fb51. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: src/sentry/android/android_util.h [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#pragma once
+
+#include <godot_cpp/variant/variant.hpp>
+
+namespace sentry::android {
+
+godot::Variant sanitize_variant(const godot::Variant &p_value, int p_depth = 0);
+
+}
```
Comment (jpnurmi) [inline src/sentry/android/android_util.h]: // namespace sentry::android

Comment (limbonaut) [reply src/sentry/android/android_util.h]: Thanks
